/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module fsm_tester_2 (
    input clk,
    input rst,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  localparam DIV = 5'h1a;
  
  localparam MAX_VALUE = 30'h23ffffff;
  
  localparam MANUAL_states = 1'd0;
  localparam AUTO_states = 1'd1;
  
  reg M_states_d, M_states_q = MANUAL_states;
  reg [28:0] M_ctr_d, M_ctr_q = 1'h0;
  
  always @* begin
    M_states_d = M_states_q;
    M_ctr_d = M_ctr_q;
    
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    
    case (M_states_q)
      MANUAL_states: begin
        M_ctr_d = 1'h1;
        io_led[0+0+0-:1] = (io_dip[0+1+0-:1] ^ io_dip[0+0+0-:1]) ^ io_dip[0+2+0-:1];
        io_led[0+1+0-:1] = ((io_dip[0+1+0-:1] ^ io_dip[0+0+0-:1]) & io_dip[0+2+0-:1]) | (io_dip[0+1+0-:1] & io_dip[0+0+0-:1]);
        if (io_button[1+0-:1]) begin
          M_states_d = AUTO_states;
        end
      end
      AUTO_states: begin
        io_led[8+0+2-:3] = M_ctr_q[26+2-:3];
        M_ctr_d = M_ctr_q + 1'h1;
        if (M_ctr_q == 1'h0) begin
          M_states_d = MANUAL_states;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
      M_states_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
      M_states_q <= M_states_d;
    end
  end
  
endmodule
